<!DOCTYPE html>
<html>
<head>
	<title>promise对象</title>
</head>
<body>

</body>
</html>
<script>
	// Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。
	// Promise 的状态一旦改变，就永久保持该状态，不会再变了。
	// 1. 基本用法
	// 如果调用resolve函数和reject函数时带有参数，那么它们的参数会被传递给回调函数。reject函数的参数通常是Error对象的实例，表示抛出的错误；resolve函数的参数除了正常的值以外，还可能是另一个 Promise 实例。
	let a=new Promise(function(resolve,reject){
		let COUNT=10;
		if(COUNT===10){
			resolve('success');
		}else{
			reject();
		}
	});
	a.then(function(val){
		console.log('resolve callback. '+val);
	},function(){
		console.log('reject callback.');
	});   //resolve callback. success

	// 例：
	function timeout(ms){
		return new Promise((resolve,reject)=>{
			setTimeout(resolve,ms,'good lucky. resolved')	
		});
	}
	timeout(2000).then((val)=>{
		console.log(val)
	});  //2s后输出 good lucky. resolved

	// 2. then方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行
	let promise=new Promise(function(resolve,reject){
		console.log('promise');
		resolve();  // 调用resolve或reject并不会终结 Promise 的参数函数的执行。
		console.log('promise down');
	});
	promise.then(function(){
		console.log('resolved.');
	});
	console.log('hi');
	function a(){
		console.log('function a');
	}
	a();
	// promise
	// promise down
	// hi
	// function a
	// resolved.

	// 3. 异步加载图片
	function loadImageAsync(url){
		return new Promise(function(resolve,reject){
			const image=new Image();
			image.onload=function(){
				resolve(image);
			};
			image.onerror=function(){
				reject(new Error('Could not load image at '+url));
			};
			image.src=url;
		});
	}

	// 4. catch
	let aa2=new Promise(function(resolve,reject){
		let COUNT=2;
		if(COUNT==1){
			resolve('resolved.')
		}else{
			reject('rejected.')
		}
	});
	aa2.then(function(val){
		console.log(val)
	}).catch(function(err){
		console.log(err)
	});  //rejected.

	// 5. 由于p2返回的是另一个 Promise，导致p2自己的状态无效了，由p1的状态决定p2的状态。
	const p1=new Promise(function(resolve,reject){
		setTimeout(()=>reject(new Error('fail')),3000);
	});
	const p2=new Promise(function(resolve,reject){
		setTimeout(()=>resolve(p1),1000);
	});
	p2.then(result=>console.log(result))
		.catch(err=>console.log(err));  //Error: fail

	// 6. 调用resolve或reject并不会终结 Promise 的参数函数的执行。
	new Promise((resolve,reject)=>{
		resolve(1);
		console.log(2)
	}).then(val=>console.log(val));  //2  //1

	// 7. Promise.prototype.finally()
	// 不管promise最后的状态，在执行完then或catch指定的回调函数以后，都会执行finally方法指定的回调函数。
	let a=new Promise((resolve,reject)=>{
		console.log('a');
		resolve('resolved.')
	});
	a.then(msg=>console.log(msg))
	 .finally(()=>console.log('finally.'));
 	// a
 	// resolved.
 	// finally.

 	// 8. 有些时候，多个异步任务是为了容错。比如，同时向两个URL读取用户的个人信息，只需要获得先返回的结果即可。这种情况下，用Promise.race()实现：
 	let p1=new Promise((resolve,reject)=>{
 		setTimeout(resolve,600,'p1');
 	});
 	let p2=new Promise((resolve,reject)=>{
 		setTimeout(resolve,500,'p2');
 	});
 	Promise.race([p1,p2]).then(res=>{
 		console.log(res);  //p2
 	});
 	
</script>

